# SPDX-FileCopyrightText: Copyright 2020-2024, Contributors to CICD
# SPDX-PackageHomePage: https://github.com/dmyersturnbull/cicd
# SPDX-License-Identifier: Apache-2.0

# Check out https://pre-commit.com/ for documentation
minimum_pre_commit_version: 3.7.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-json
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
        exclude: ^recipes/.*
        args:
          - --unsafe
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: [--remove]
      - id: check-illegal-windows-names
      - id: forbid-submodules
      - id: trailing-whitespace

  # --- Commit msg checks ---
  - hooks:
      - id: commitizen
        stages: ["commit-msg"]
    repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0

  # --- Linters ---
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff
        args: [--fix-only]
        types_or: [python, pyi, jupyter]
