# Check out https://pre-commit.com/ for documentation
# and https://pre-commit.com/hooks.html for more hooks
minimum_pre_commit_version: 2.10.0
# Don't set language_version -- it's only useful if we have multiple
# python versions or our build uses a different env than runtime
repos:
  # --- Built-in hooks --
  - hooks:
      - id: check-symlinks
      - id: check-case-conflict
      - id: fix-byte-order-marker
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-toml
      - id: check-json
      - id: check-yaml
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
