site_name: "Gaslit by a computer"
docs_dir: "contents"
site_dir: "docs"

copyright: Copyright 2023, Douglas Myers-Turnbull
site_description: "Software guides, reference docs, and more."

# Navigation menu
nav:
  - Home: index.md
  - Reference docs:
      - Contributor guide: ref/contributor-guide.md
      - Maintainer guide: ref/maintainer-guide.md
      - Issue labels: ref/github-labels.md
  - Conventions:
      - Overview: convention/index.md
      - Documentation: convention/documentation.md
      - APIs: convention/apis.md
      - Scripts and build files: convention/scripts-and-build-files.md
      - Python: convention/python.md
      - Java: convention/java.md
      - JavaScript: convention/javascript.md
      - SQL: convention/sql.md
  - Specifications:
      - Advanced BNF with regex: spec/advanced-bnf-with-regex.md
      - HTTP GET search DSL: spec/http-get-search-dsl.md
      - HATEOAS `See` header: spec/hateoas-see-header.md
  - Setup guides:
      - Linux: guide/linux.md
      - macOS: guide/macos.md
      - Windows: guide/windows.md
      - Git, SSH, and GPG: guide/git-ssh-gpg.md
      - Research projects: guide/research-projects.md
      - MariaDB: guide/mariadb.md
      - Mamba and Conda: guide/mamba-and-conda.md
      - FFmpeg: guide/ffmpeg.md
      - Arduino: guide/arduino.md
  - Posts & tutorials:
      - Duck typing is quackery: post/duck-typing-is-quackery.md
      - Software test strategy guide: post/software-testing-strategy-guide.md
      - Testing scientific software: post/testing-scientific-software.md
      - Python infrastructure: post/retooling-python-builds.md
      - Frontends for time-travelers: post/frontends-for-time-travelers.md
      - Git tips and microscripts: post/git-tips-and-microscripts.md
      - Wonders of ChatGPT: post/wonders-of-chatgpt.md

# Theme
theme:
  name: material
  features:
    - content.action.edit
    - content.code.copy
    - content.code.annotate
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - tags
    - toc.follow
    - typeset
  #icon:
  #  logo: material/thunderstorm
  #  repo: fontawesome/brands/github
  #favicon:
  #  logo: material/thunderstorm
  #  repo: fontawesome/brands/github
  font:
    text: Noto Sans
    code: Noto Sans Mono
  static_templates:
    - 404.html
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  # :tyranno: repo_url: ${project.urls.Source}
  repo_url: https://github.com/dmyersturnbull/cicd
  extra:
    consent:
      title: Cookie consent
      description: >-
        This site uses cookies to remember your preferences and to enable analytics.
        Please indicate your consent.
      actions: [accept, reject, manager]

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.betterem:
      smart_enable: all
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - markdown_include.include:
      base_path: contents
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      guess_lang: false
      linenums_style: pymdownx-inline
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shortener: true
      social_url_shorthand: true
      normalize_issue_symbols: true
      provider: github
      # :tyranno: user: ${.vendor}
      user: dmyersturnbull
      # :tyranno: repo: ${project.name}
      repo: dmyersturnbull.github.io
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      #slugify: !!python/object/apply:pymdownx.slugs.slugify
      #  kwds:
      #    case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - smarty
  - tables
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

plugins:
  - search
  - table-reader
  - mkdocstrings:
      handlers:
        python:
          options:
            show_submodules: true
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      cache_safe: true
