site_name: "Gaslit by a computer"
docs_dir: "contents"
site_dir: "docs"

copyright: Copyright 2023, Douglas Myers-Turnbull
site_description: "Gaslit by a computer"

# Navigation menu
nav:
  - Home: index.md
  - Contributing guide: contributing-guide.md
  - Coding conventions: coding-conventions.md
  - Linux setup: linux-setup.md
  - macOS setup: macos-setup.md
  - Windows setup: windows-setup.md
  - MariaDB best practices: mariadb-best-practices.md
  - MariaDB local install: mariadb-local-install.md
  - Software testing (post): software-testing.md
  - Python infrastructure (post): python-infrastructure.md
  - Web stuff (_draft_): web-stuff.md
  - Research layout (_draft_): web-stuff.md
  - Video encoding (_draft_): video-encoding.md
  - Parser design (_draft_): parser-design.md

# Theme
theme:
  name: material
  features:
    - tabs
    - content.action.edit
    - content.code.copy
    - content.code.annotate
  icon:
    logo: material/cloud
    repo: fontawesome/brands/github
  font:
    text: Noto Sans
    code: Noto Sans Mono
  static_templates:
    - 404.html
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  # :tyranno: repo_url: ${project.urls.Source}
  repo_url: https://github.com/dmyersturnbull/cicd
  extra:
    consent:
      title: Cookie consent
      description: >-
        This site uses cookies to remember your preferences and to enable analytics.
        Please indicate your consent.
      actions: [accept, reject, manager]

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.betterem:
      smart_enable: all
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      guess_lang: false
      linenums_style: pymdownx-inline
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shortener: true
      social_url_shorthand: true
      normalize_issue_symbols: true
      provider: github
      # :tyranno: user: ${.vendor}
      user: dmyersturnbull
      # :tyranno: repo: ${project.name}
      repo: cicd
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - smarty
  - tables
  - toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_submodules: true
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      cache_safe: true
